# Monitoring controls configurations

## Cloudtrail / Trails values
trail.name: some-name
s3bucket.name: any-name-with-dashes
trail_arn.id: arn:aws:cloudtrail:us-east-1:484747447281:trail/some-name
cloudwatch.logs.role.arn: arn:aws:iam:::role/CloudTrail_CloudWatchLogs_Role
cloudwatch.logs.log_group.arn: arn:aws:logs:us-east-1::log-group:test:*
kms.key.id: key-arn
home.region.id: us-east-1
### Trails values
cloudtrail.entries: 100
cloudtrail.name.list:
  - some-name 1
  - some-name 2
cloudtrail.arn.list:
  - arn:aws:cloudtrail:us-east-1::trail/trail-1
  - arn:aws:cloudtrail:us-east-1::trail/trail-2
## Cloudwatch Alarm / Log Filtering values



## Config Recorder values
